package com.airbnb.skipper.hello;

import static org.mockito.Mockito.mock;

import com.airbnb.skipper.Actions;
import com.airbnb.skipper.Execute;
import com.airbnb.skipper.Workflow;
import com.airbnb.skipper.WorkflowFactory;
import com.airbnb.skipper.WorkflowMethod;
import java.util.concurrent.CompletableFuture;
import lombok.Builder;
import lombok.Value;

/**
 * A workflow class that coordinates greeting and farewell operations. This workflow encapsulates
 * the process of generating personalized messages.
 *
 * <p>The workflow leverages the HelloActions and FarewellActions classes to execute the actions.
 */
class HelloWorkflowJava extends Workflow {
  private final HelloActionsJava helloActions = actions(HelloActionsJava.class);
  private final FarewellActionsJava farewellActions = actions(FarewellActionsJava.class);

  /**
   * A class to encapsulate the request information for generating a greeting and farewell. It
   * contains a field 'name' which represents the name of the person to address, which will be
   * included in the messages.
   */
  @Value
  @Builder
  public static class HelloRequest {
    String name;
  }

  /**
   * Data class to encapsulate the response from greeting and farewell operations. It contains
   * fields 'greeting' and 'farewell' which represents the complete messages generated by the
   * workflow.
   */
  @Value
  @Builder
  public static class HelloResponse {
    String greeting;
    String farewell;
  }

  /**
   * Executes the workflow to generate greeting and farewell messages. This method is the entry
   * point for the workflow.
   *
   * @param request The HelloRequest containing the name of the person to greet.
   * @return Returns a HelloResponse containing the personalized messages.
   */
  @WorkflowMethod(returnType = HelloResponse.class)
  public CompletableFuture<HelloResponse> hello(HelloRequest request) {
    CompletableFuture<String> helloFuture = helloActions.sayHello(request.getName());
    CompletableFuture<String> byeFuture = farewellActions.sayBye(request.getName());

    return helloFuture.thenCombine(byeFuture, HelloResponse::new);
  }
}

/**
 * A private class defining actions related to generating greetings. This class provides the
 * essential functionality required by the HelloWorkflow to execute its greeting logic.
 */
class HelloActionsJava extends Actions {
  /**
   * Generates a greeting message for a given name. This method performs a significant action within
   * the workflow.
   *
   * @param name The name of the person to greet.
   * @return Returns a greeting string addressed to the specified name.
   */
  @Execute(returnType = String.class)
  public CompletableFuture<String> sayHello(String name) {
    return CompletableFuture.completedFuture("Hello, " + name + "!");
  }
}

/**
 * A private class defining actions related to generating farewells. This class provides the
 * essential functionality required by the HelloWorkflow to execute its farewell logic.
 */
class FarewellActionsJava extends Actions {
  /**
   * Generates a bye message for a given name. This method performs a significant action within the
   * workflow.
   *
   * @param name The name of the person to say bye to.
   * @return Returns a bye string addressed to the specified name.
   */
  @Execute(returnType = String.class)
  public CompletableFuture<String> sayBye(String name) {
    return CompletableFuture.completedFuture("Bye, " + name + "!");
  }
}

/**
 * Demonstrates the usage of the HelloWorkflow to generate and print a greeting message. This
 * function instantiates the workflow and sends a greeting request with a specified name.
 */
class HelloWorkflowJavaMain {
  public static void main(String[] args) {
    WorkflowFactory workflowFactory = mock(WorkflowFactory.class);

    workflowFactory
        .invoke(HelloWorkflowJava.class, "test")
        .hello(new HelloWorkflowJava.HelloRequest("John Wick"))
        .thenAccept(
            response -> {
              System.out.println(response.getGreeting());
              System.out.println(response.getFarewell());
            });
  }
}
