package com.airbnb.skipper.hello

import com.airbnb.skipper.Actions
import com.airbnb.skipper.Execute
import com.airbnb.skipper.Workflow
import com.airbnb.skipper.WorkflowFactory
import com.airbnb.skipper.WorkflowMethod
import com.airbnb.skipper.invoke
import org.mockito.kotlin.mock

/**
 * A workflow class that coordinates greeting and farewell operations. This workflow encapsulates the
 * process of generating personalized messages.
 *
 * The workflow leverages [HelloActions] and [FarewellActions] classes to execute the actions.
 *
 * @property helloActions An instance of [HelloActions] used to access the greeting functionality.
 * @property farewellActions An instance of [FarewellActions] used to access the farewell functionality.
 */
private class HelloWorkflow : Workflow() {
    private val helloActions = actions<HelloActions>()
    private val farewellActions = actions<FarewellActions>()

    /**
     * Data class to encapsulate the request information for generating a greeting and farewell.
     * @param name The name of the person to address, which will be included in the messages.
     */
    data class HelloRequest(val name: String)

    /**
     * Data class to encapsulate the response from greeting and farewell operations.
     * @param greeting The complete greeting message generated by the workflow.
     * @param farewell The complete farewell message generated by the workflow.
     */
    data class HelloResponse(val greeting: String, val farewell: String)

    /**
     * Executes the workflow to generate greeting and farewell messages. This method is the entry point
     * for the workflow, annotated as a workflow method to indicate its role in the orchestration.
     *
     * @param request The [HelloRequest] containing the name of the person to greet.
     * @return Returns a [HelloResponse] containing the personalized messages.
     */
    @WorkflowMethod
    suspend fun hello(request: HelloRequest): HelloResponse {
        return HelloResponse(
            greeting = helloActions.sayHello(request.name),
            farewell = farewellActions.sayBye(request.name)
        )
    }
}

/**
 * A private class defining actions related to generating greetings. This class provides the essential
 * functionality required by the [HelloWorkflow] to execute its greeting logic.
 */
private class HelloActions : Actions() {
    /**
     * Generates a greeting message for a given name. This method is marked with the [Execute] annotation
     * to denote that it performs a significant action within the workflow.
     *
     * @param name The name of the person to greet.
     * @return Returns a greeting string addressed to the specified name.
     */
    @Execute
    suspend fun sayHello(name: String): String {
        return "Hello, $name!"
    }
}

/**
 * A private class defining actions related to generating farewells. This class provides the essential
 * functionality required by the [HelloWorkflow] to execute its farewell logic.
 */
private class FarewellActions : Actions() {
    /**
     * Generates a bye message for a given name. This method is marked with the [Execute] annotation
     * to denote that it performs a significant action within the workflow.
     *
     * @param name The name of the person to say bye to.
     * @return Returns a bye string addressed to the specified name.
     */
    @Execute
    suspend fun sayBye(name: String): String {
        return "Bye, $name!"
    }
}

/**
 * Demonstrates the usage of the [HelloWorkflow] to generate and print messages. This function
 * instantiates the workflow and sends a request with a specified name.
 *
 * This is a utility function designed to showcase how the workflow and multiple actions are orchestrated
 * to perform the greeting operation.
 */
@Suppress("unused")
private suspend fun useHelloWorkflow() {
    val workflow = mock<WorkflowFactory>()
    val requestContext = null

    val response =
        workflow<HelloWorkflow>("test", requestContext).hello(
            HelloWorkflow.HelloRequest(name = "John Wick")
        )
    println("${response.greeting} ${response.farewell}")
}
